# Copyright (c) 2022 anatawa12 and other contributors
# This file is part of *All Config Syncer, released under MIT License
# See LICENSE at https://github.com/freedom-mod-development-community/asta-all-config-syncer for more details

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: build
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: ./build/libs/*
          retention-days: 30

      # get jar name
      - name: prepare run server
        id: prepare_run_server
        run: |
          echo "::set-output name=version_name::$(grep 'modVersion=' < gradle.properties | sed 's/modVersion=//')"

      - name: run server
        uses: anatawa12/minecraft-server-start-test@v1
        with:
          version: 1.12.2-14.23.5.2855
          mod_jar: ./build/libs/asta-all-config-syncer-${{ steps.prepare_run_server.outputs.version_name }}.jar
          mods_dir: mods
